#!/usr/bin/with-contenv sh

# load network variables
source /root/.profile

# change chdir
cd /config

# run with limited permissions
exec s6-setuidgid $PUID:$PGID deluge-web --loglevel none --do-not-daemonize --config=/config --interface="$LAN_IP"
