#!/usr/bin/with-contenv sh

LOGS_DIR="/config/logs"

# check if logs folder exists and create it
if [[ ! -d "$LOGS_DIR" ]]; then
  install -dm755 -o $PUID -g $PGID "$LOGS_DIR"
fi


# load network variables
source /root/.profile

LOGS_DIR="/config/logs"

# check if logs folder exists and create it
if [[ ! -d "$LOGS_DIR" ]]; then
  install -dm755 -o $PUID -g $PGID "$LOGS_DIR"
fi

# change chdir
cd /config

# run with limited permissions
exec s6-setuidgid $PUID:$PGID deluged \
    --do-not-daemonize \
    --config=/config \
    --loglevel info --logfile="$LOGS_DIR/deluge.log" \
    --read-only-config-keys=outgoing_interface \
    --outgoing-interface="$WG_DEV"
