#!/usr/bin/with-contenv sh

LOGS_DIR="/config/logs"

# check if logs folder exists and create it
if [[ ! -d "$LOGS_DIR" ]]; then
  install -dm755 -o $PUID -g $PGID "$LOGS_DIR"
fi


# load network variables
source /root/.profile

# run with limited permissions (from /usr/local/bin)
exec deluged \
    --loglevel info \
    --read-only-config-keys="outgoing_interface" \
    --outgoing-interface="$WG_DEV"
